#!/bin/sh

VERSION='0.2'
USERDIR='/home/warlock'
CODEDIR='files/Code/cpp'

echo "********************************************************"
echo "<Project> dependency updater."
echo ""
echo "Installer version: ${VERSION}"
echo ""
echo "Copying files."
echo ""
echo "Updating Dependencies! Pulling files.."
echo ""
cp -f ${USERDIR}/${CODEDIR}/ds/Dice/stable/* unstable/
echo ""
echo "Done copying files."
echo ""
